### ISSUE TITLE
Override button colors

### ISSUE THREAD

**Issue by tophsic** [helpscout/seed-button#12]
Hi,

I am really instered in seed framework but I can not find a way to override some default configuration.

Here is a extract of my Sass code:

```scss
@import "pack/seed-color-scheme/_index";
@import "pack/seed-dash/_index";
@import "pack/seed-button/_index";

$colors: (
  orange: (
    default: #EC6F35,
  )
);

$button-styles-primary: _color(orange, default);
$seed-button-styles: _set($seed-button-styles, primary, background, default, $button-styles-primary);
```

I use seed-harvester on my webpack configuration.

I did not find how to do it on Seed project documentation or a concrete example.

Thank you for your help.

**Comment by ItsJonQ** [comment]
@tophsic Haii! Thanks for checking out Seed!

Oh wow! You've gotten a lot of it setup already. That's awesome! 🙌
Apologies for the sparse documentation on some of the more advanced technique. I'm hoping to write guides and things as soon as I can!

As of right now, it's a bit of setup to adjust button colors (more details after code example). Here's something you can do:

```scss
// Importing dependencies for seed-button color customization
@import "pack/seed-color-scheme/_index";
@import "pack/seed-dash/_index";
@import "pack/seed-button/config";


// Defining custom config for colors
$colors: (
  orange: (
    default: #EC6F35,
  )
);
// SETTING them! :)
@include _color($colors);


// Overidding the default button styles
$seed-button-styles: _deep-extend($seed-button-styles, (
  primary: (
    background: (
      default: _color(orange),
    )
  ),
));


// ...

// Somewhere later in your SCSS imports flow
@import "pack/seed-button/_index";
```

Sass variables are… finicky. You can adjust them however it is you want, only up to the point where rules use them.

In the example above, the top portion deals only with variable adjustments. We're only importing the variables from `seed-button`. Later on in the Sass setup, we have the actual CSS styles being generated.

Compared to other Sass-based approaches, this may seem a little… intimidating 😨 , especially `seed-button` (as buttons are one of the most complicated UI components, IMO). I'm glad you mentioned webpack, as this approach is sorta similar in that, they may be some setup stuff in the beginning (depending on how much you wanna customize), but it scales very well over time.

Hopefully this was helpful! Please let me know if you have any more questions :D


P.S. Also! `seed-color-scheme` was [recently updated](https://github.com/helpscout/seed-color-scheme/releases/tag/v0.1.0) to come with colours out of the box. My plan was to go back and adjust other packs (like `seed-button`) to make it much easier to adjust colour things.

P.P.S. Very curious! How did you find out about Seed? :D!

P.P.P.S. Some fun `seed-color-scheme` facts!

```scss
// You can set colors "inline" without having to define a variable

// Before
$colors: (
  orange: (
    default: #EC6F35,
  )
);
@include _color($colors);

// After
@include _color((
  orange: (
    default: #EC6F35,
  )
));
```

If a color has a `default` key, you don't need to say `default` when you use the `_color()` function. Example:

```scss
.button {
  color: _color(orange); // same thing as _color(orange, default)
}
```

**Comment by ItsJonQ** [comment]
O! And of course, if you have any suggestions, please let me know!! :D

**Comment by tophsic** [comment]
Many thx for your response @ItsJonQ 

Firstly, I found Seed after googling because I was beginning a new project (business web app) from scratch and wanted to choose a good style organisation. I am not a frontend expert but I am interested in the packages philosophy of Seed. I am still evaluating if I can use it but it seems promising. It is funny because on the other side, we are Helpscout customer.

All the details you gave me are precious. I had following error on testing your code but resolved it on updating `seed-color-scheme` (from `0.0.2` to `0.1.0`).

```
Module build failed: 
    $map: map-get($map, $key);
         ^
      Argument `$map` of `map-get($map, $key)` must be a map

Backtrace:
        node_modules/seed-color-scheme/scss/pack/seed-color-scheme/functions/_color.scss:12, in function `map-get`
        node_modules/seed-color-scheme/scss/pack/seed-color-scheme/functions/_color.scss:12, in function `_color`
        app/styles/Header.scss:4
      in /home/christophe/Dev/next/mapstime-techniciens/node_modules/seed-color-scheme/scss/pack/seed-color-scheme/functions/_color.scss (line 12, column 11)
```

The tips are very welcome. For sure I will follow evolution of Seed.

**Comment by ItsJonQ** [comment]
@tophsic Awesome! Feel free to reach out anytime if you have anymore questions :D. Thanks a bunch again for checking out Seed! We've been using it internally for long time now, and haven't only started surfacing things publicly. Started with basic docs, but need to write guides and such

I'm glad you like the philosophy behind it! That was something I wanted to bring into the world of CSS… philosophies and best practices from other coding languages 👍 

Something that makes CSS more understandable (from a scaling standpoint) for more dev-focused folks :).
